export enum HeroNames {
    "Kaja" = "Кайя",
    "Ming" = "Минь",
    "Afina" = "Афина",
    "Bella_And_Sam" = "Белла и Сэм",
    "Atilla" = "Атилла",
    "Malxaz" = "Малхаз",
    "Amanta" = "Аманта",
    "Rocky" = "Рокки",
    "Alex" = "Алекс",
    "Misoko" = "Мисоко",
    "Diana" = "Диана",
    "Omar" = "Омар",
    "Lucius" = "Луций",
}
